config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :contacts_files, only: [:index, :show]
  resources :contacts
  get 'import-contacts', to: 'contacts#import_contacts', as: 'import_contacts'

  is_ajax_request = ->(request) { request.xhr? }
  post 'pre-parse-contacts', to: 'contacts#pre_parse_contacts', constraint: is_ajax_request,
                             as: 'pre_parse_contacts'

  post 'import-contacts-submit', to: 'contacts#import_contacts_submit', constraint: is_ajax_request,
                                 as: 'import_contacts_submit'

  root 'contacts#import_contacts'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/batch_row.rb
# frozen_string_literal: true

# Model to store row of a batch for background processing of imports
class BatchRow < ApplicationRecord
  serialize :data
  belongs_to :contacts_file
end

app/models/concerns/mapping_validator.rb
# frozen_string_literal: true

# Validates the mapping of CSV files
class MappingValidator < ActiveModel::Validator
  def validate(record)
    mapping_config = JSON.parse(record.mapping_config)
    repeated_values = mapping_config.group_by { |_k, v| v }.select { |_k, v| v.count > 1 }
    record.errors.add(:mapping, 'duplicated mapping') unless repeated_values.empty?
  end
end

app/models/concerns/name_validator.rb
# frozen_string_literal: true

# Validates the name of a Contact
class NameValidator < ActiveModel::Validator
  def validate(record)
    record.errors.add(:name, 'special characters not allowed') if record.name.match(/^[\-A-Za-z0-9 .&]*\z/).nil?
  end
end

app/models/contact.rb
# frozen_string_literal: true

# Contacts model
class Contact < ApplicationRecord
  validates :name, presence: { message: 'Name is required' }
  validates_with NameValidator, if: :name_present?

  private

  def name_present?
    name.present?
  end
end

app/models/contacts_file.rb
# frozen_string_literal: true

# This model holds record of the uploaded files
class ContactsFile < ApplicationRecord
  attr_accessor :file

  has_many :batch_rows

  mount_uploader :file, FileUploader

  validates_with MappingValidator

  def enqueue_parsing
    puts '------- Callback Start -------'
    return if status == 'Processed'

    puts '------- Worker exec -------'
    BatchWorker.perform_async(id)
    # TODO: Track worker to know when it has finished.
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contacts_controller.rb
# frozen_string_literal: true

# Contacts Controller
class ContactsController < ApplicationController
  before_action :set_contact, only: %i[show edit update destroy]

  # GET /contacts or /contacts.json
  def index
    @contacts = Contact.all
  end

  def import_contacts; end

  def pre_parse_contacts
    @headers = params[:file_headers].split(',')
    @contacts_columns = Contact.column_names.dup # We need to duplicate to avoid frozen array error

    # Delete unwanted columns
    @contacts_columns.delete('id')
    @contacts_columns.delete('created_at')
    @contacts_columns.delete('updated_at')
    @contacts_columns.delete('franchise')

    respond_to do |format|
      format.js
    end
  end

  def import_contacts_submit
    @new_file = ContactsFile.new(contacts_file_params)
    respond_to do |format|
      @new_file.save
      format.js
      format.json { render json: @new_file.errors, status: :unprocessable_entity } if @new_file.has_errors?
    end
  end

  # GET /contacts/1 or /contacts/1.json
  def show; end

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # GET /contacts/1/edit
  def edit; end

  # POST /contacts or /contacts.json
  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to @contact, notice: 'Contact was successfully created.' }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1 or /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to @contact, notice: 'Contact was successfully updated.' }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1 or /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url, notice: 'Contact was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_contact
    @contact = Contact.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def contact_params
    params.require(:contact).permit(:name, :date_of_birth, :phone, :address, :creditcard, :franchise, :email)
  end

  def contacts_file_params
    params.permit(:file, :mapping_config)
  end
end

app/controllers/contacts_files_controller.rb
# frozen_string_literal: true

# Controller of the ContactsFile model
class ContactsFilesController < ApplicationController
  def index
    @contacts_files = ContactsFile.all
  end

  def show
    @contacts_file = ContactsFile.find(params[:id])
    @error_rows = @contacts_file.batch_rows.where(has_errors: true)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/_form.html.erb
<%= form_with(model: contact) do |form| %>
  <% if contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
        <% contact.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :date_of_birth %>
    <%= form.text_field :date_of_birth %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.text_field :phone %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address %>
  </div>

  <div class="field">
    <%= form.label :creditcard %>
    <%= form.text_field :creditcard %>
  </div>

  <div class="field">
    <%= form.label :franchise %>
    <%= form.text_field :franchise %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/contacts/edit.html.erb
<h1>Editing Contact</h1>

<%= render 'form', contact: @contact %>

<%= link_to 'Show', @contact %> |
<%= link_to 'Back', contacts_path %>

app/views/contacts/import_contacts.html.erb
<h1>Import Contacts</h1>
<div class='container import-contacts-container'>
  <%= label_tag 'file', 'Upload your CSV file' %>
  <%= file_field_tag :file, accept: 'text/csv', id: 'contacts_file_field' %>
  <%= button_tag 'Import', class: 'upload-contacts-button' %>
</div>
<div id='load-mapping-columns'>
  <%= form_tag import_contacts_submit_path, id: 'fields-map-form' do %>
  <div class="form-table">
  </div>
  <%= submit_tag 'Finish Import', class: 'hidden submit-contacts', data: { disable_with: false } %>
  <% end %>
</div>
<div class="import-result"></div>

app/views/contacts/import_contacts_submit.js.erb
<% if @new_file.errors.any? %>
  <% @new_file.errors.each do |error| %>
    $(".import-result").text("<%= error.full_message %>")
  <% end %>
<% else %>
  $(".import-result").text("Your import is in queue!")
<% end %>

app/views/contacts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Contacts</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Date of birth</th>
      <th>Phone</th>
      <th>Address</th>
      <th>Creditcard</th>
      <th>Franchise</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @contacts.each do |contact| %>
      <tr>
        <td><%= contact.name %></td>
        <td><%= contact.date_of_birth %></td>
        <td><%= contact.phone %></td>
        <td><%= contact.address %></td>
        <td><%= contact.creditcard %></td>
        <td><%= contact.franchise %></td>
        <td><%= contact.email %></td>
        <td><%= link_to 'Show', contact %></td>
        <td><%= link_to 'Edit', edit_contact_path(contact) %></td>
        <td><%= link_to 'Destroy', contact, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Contact', new_contact_path %>

app/views/contacts/new.html.erb
<h1>New Contact</h1>

<%= render 'form', contact: @contact %>

<%= link_to 'Back', contacts_path %>

app/views/contacts/pre_parse_contacts.js.erb
$('#load-mapping-columns form .form-table').html("<table><caption>Map CSV fields to Contacts</caption><thead><th>Column name</th><th>Map to field</th></thead><tbody><% @headers.each_with_index do |header, index| %><tr><td id='<%= "config-mapping-header-#{index}" %>'><%= header %></td><td><select id='<%= "config-mapping-column-#{index}" %>' ><% @contacts_columns.each do |column| %><option value='<%= column %>'><%= column %></option><% end %></select></td></tr><% end %></tbody></table>")

app/views/contacts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @contact.name %>
</p>

<p>
  <strong>Date of birth:</strong>
  <%= @contact.date_of_birth %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @contact.phone %>
</p>

<p>
  <strong>Address:</strong>
  <%= @contact.address %>
</p>

<p>
  <strong>Creditcard:</strong>
  <%= @contact.creditcard %>
</p>

<p>
  <strong>Franchise:</strong>
  <%= @contact.franchise %>
</p>

<p>
  <strong>Email:</strong>
  <%= @contact.email %>
</p>

<%= link_to 'Edit', edit_contact_path(@contact) %> |
<%= link_to 'Back', contacts_path %>

app/views/contacts_files/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Uploaded Files</h1>
<div class="container">
  <ul>
    <% @contacts_files.each do |contacts_file| %>
    <li id="<%= dom_id(contacts_file) %>" class="contacts-file">
      <%= link_to "#{contacts_file.file_identifier}", contacts_file %>
      <small><%= contacts_file.status %> | Uploaded at: <%= contacts_file.created_at.strftime('%d %b. %Y %H:%M') %></small>
    </li>
    <% end %>
  </ul>
</div>

app/views/contacts_files/show.html.erb
<p id="notice"><%= notice %></p>
<h1><%= @contacts_file.file_identifier %></h1>
<% if @contacts_file.has_errors? %>
<p>Some rows have errors</p>
<div class="container">
  <table class="error-rows">
    <thead>
      <th>Row #</th>
      <th>Name</th>
      <th>Date of birth</th>
      <th>Phone</th>
      <th>Address</th>
      <th>Credit Card</th>
      <th>Email</th>
      <th>Error description</th>
    </thead>
    <tbody>
      <% @error_rows.each do |row| %>
      <tr id="<%= dom_id(row) %>" class="error-row">
        <td><%= row.row %></td>
        <td><%= row.data[:name] %></td>
        <td><%= row.data[:date_of_birth] %></td>
        <td><%= row.data[:phone] %></td>
        <td><%= row.data[:address] %></td>
        <td><%= row.data[:creditcard] %></td>
        <td><%= row.data[:email] %></td>
        <td><%= row.error_messages %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ContactsImporter</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= yield %>
  </body>
</html>